---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.envoyConfig.gatewayClass }}
spec:
  controllerName: {{ .Values.envoyConfig.controllerName }}
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: {{ .Release.Name }}-envoy-proxy
    namespace: {{ .Release.Namespace }}