
argo-workflows:
  workflow:
    serviceAccount:
      create: true
      name: "argo-workflow"
    rbac:
      create: true
  server:
    authModes:
    - server
    secure: false 
    httproute:
      enabled: true
      hostnames:
      - workflows.synera.com.br
      parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: envoy-gateway-envoy-gateway
        namespace: envoy-gateway-system
        sectionName: http
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: envoy-gateway-envoy-gateway
        namespace: envoy-gateway-system
        sectionName: https
      rules:
      - backendRefs:
        - group: ""
          kind: Service
          name: argo-workflow-argo-workflows-server
          port: 2746
          weight: 1
        matches:
        - path:
            type: PathPrefix
            value: /

