
argo-workflows:
  workflow:
    serviceAccount:
      create: true
      name: "argo-workflow"
    rbac:
      create: true
  server:
    # authModes:
    # - server
    secure: false 
    httproute:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: "186.216.247.16"
      hostnames:
      - workflows.synera.com.br
      parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: https
        namespace: envoy-gateway
        # http listener (port 80) - used for internal/local access
        sectionName: http
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: https
        namespace: envoy-gateway
        # https listener (port 443) - used for external access via router/NAT
        sectionName: https
      rules:
      - backendRefs:
        - group: ""
          kind: Service
          name: argo-workflow-argo-workflows-server
          port: 2746
          weight: 1
        matches:
        - path:
            type: PathPrefix
            value: /

