apiVersion: v2
name: envoy-gateway
description: A Helm chart for deploying the Gateway API components, including the Envoy Gateway and its dependencies.
keywords:
  - gateway-api
  - envoyproxy
  - envoy-gateway
  - eg
type: application
version: "1.0.0"
appVersion: "1.0.0"
dependencies:
  - name: gateway-helm
    version: 1.7.0
    repository: oci://docker.io/envoyproxy