# gateway-crds-helm:
#   crds:
#     envoyGateway:
#       enabled: true
#     gatewayAPI:
#       channel: standard
#       enabled: true

gateway-helm:
  global:
    imageRegistry: ""
    imagePullSecrets: []

  commonLabels:
   type: addons

  deployment:
    replicas: 1

  hpa:
    enabled: true
    maxReplicas: 5

  config:
    extensionApis: {}
    envoyGateway:
      gateway:
        controllerName: gateway.envoyproxy.io/gatewayclass-controller
      provider:
        type: Kubernetes
      logging:
        level:
          default: info

envoyConfig:
  envoyServiceType: LoadBalancer
  envoyServiceName: envoy-gateway-service
  gatewayClass: envoy-gateway-class
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  serviceAnnotations:
    enabled: false
    annotations:
      metallb.io/address-pool: ip-address-pool-external

externalIP:
  enabled: false
  address: YOUR-EXTERNAL-IP

argocd:
  enabled: true
  hostnames:
    - gitops.synera.com.br