postgresql:
  global:
    storageClass: ""
  auth:
    database: "homelab"
    username: "admin"
    password: "changeme"
  primary:
    # No chart da Bitnami, para usar emptyDir em vez de PVC:
    persistence:
      enabled: false
    # Isso garante que ele não tente criar o VolumeClaimTemplate
    extraVolumes:
      - name: data
        emptyDir:
          medium: "Memory"
    extraVolumeMounts:
      - name: data
        mountPath: /bitnami/postgresql
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
