harbor:
  ipFamily:
    ipv4:
      enabled: "true"
    ipv6:
      enabled: "false"

  externalURL: https://registry.synera.com.br
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  database:
    type: external
    external:
      host: postgresql.database.svc.cluster.local
      port: "5432"
      username: harbor
      coreDatabase: harbor
      # A chave dentro do secret DEVE ser "password" (exigência do chart)
      existingSecret: harbor-db-secret
      sslmode: disable



  persistence:
    enabled: true
    resourcePolicy: "keep"
    persistentVolumeClaim:

      # database:
      #     existingClaim: "harbor-shared-pvc"
      #     subPath: "database"

      registry:
        existingClaim: "registry-pvc"
      # database interno desabilitado (usando external)
      # database:
      #   existingClaim: "database-pvc"
      
      jobservice:
        jobLog:
          existingClaim: "harbor-shared-pvc"
          subPath: "jobservice"
      
      redis:
        existingClaim: "harbor-shared-pvc"
        subPath: "redis"
      
      trivy:
        existingClaim: "harbor-shared-pvc"
        subPath: "trivy"

    imageChartStorage:
      type: filesystem


  expose:
    type: route
    tls:
      enabled: true
      certSource: none
    route:
      parentRefs:
        - name: internal-https
          namespace: envoy-gateway
          sectionName: internal-https
          group: gateway.networking.k8s.io
          kind: Gateway
      hosts:
        - registry.synera.com.br