harbor:
  ipFamily:
    ipv4:
      enabled: "true"
    ipv6:
      enabled: "false"

  externalURL: https://registry.synera.com.br
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  persistence:
    enabled: true
    resourcePolicy: "keep"
    persistentVolumeClaim:
      registry:
        existingClaim: "registry-pvc"
      database:
        existingClaim: "database-pvc"
      
      jobservice:
        jobLog:
          existingClaim: "harbor-shared-pvc"
          subPath: "jobservice"
      
      redis:
        existingClaim: "harbor-shared-pvc"
        subPath: "redis"
      
      trivy:
        existingClaim: "harbor-shared-pvc"
        subPath: "trivy"

    imageChartStorage:
      type: filesystem


httpRoute:
  enabled: true
  hostnames:
  - registry.synera.com.br
  externalDNSTarget: "186.216.247.16"