{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    external-dns.alpha.kubernetes.io/target: {{ $.Values.httpRoute.externalURL | default "" | quote }}
  name: harbor-https
spec:
  hostnames:
    {{- range .Values.httpRoute.hostnames }}
  - {{ . }}
    {{- end }}
  parentRefs:
    - name: https
      namespace: {{ .Values.httpRoute.namespace }}
      sectionName: https
    - name: http
      namespace: {{ .Values.httpRoute.namespace }}
      sectionName: http
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - group: ""
      kind: Service
      name: harbor-portal
      namespace: harbor
      port: 80
      weight: 1
{{- end }}