apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.acme.email }}
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token