apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: my-issuer
spec:
  acme:
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token