---
cert-manager:
  crds:
    enabled: true
  global:
    leaderElection:
      namespace: cert-manager
  config:
    enableGatewayAPI: true

acme:
  email: invalid@email.com

certificates:
  dnsNames:
  - invalid.domain