apiVersion: v2
name: opentelemetry
description: OpenTelemetry Collector Helm chart for Kubernetes
keywords:
  - opentelemetry
  - monitoring
  - collector
type: application
version: "1.0.0"
appVersion: "1.0.0"
dependencies:
  - name: opentelemetry-collector
    version: 0.152.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts