opentelemetry-collector:
  image:
    repository: otel/opentelemetry-collector
  mode: deployment
  replicaCount: 1
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
      batch:
    exporters:
      debug:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        metrics: {}
        logs: {}
