opentelemetry-collector:
  mode: deployment
  replicaCount: 1
  config:
    receivers:
      jaeger: null
      prometheus: null
      zipkin: null
    service:
      pipelines:
        traces:
          receivers:
            - otlp
        metrics: null
        logs: null