# kube-proxy-servicemonitor.yaml
# Prometheus ServiceMonitor for kube-proxy
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-proxy
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
    - port: "10249"
      interval: 30s
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: kube-proxy