apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTLSPolicy
metadata:
  name: argo-workflows-tls
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: argo-workflow-argo-workflows-server
  tls:
    validation:
      wellKnownCACertificates: System