---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-gateway-tls
  namespace: envoy-gateway-system
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  secretName: secret-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "*.synera.com.br"
    - "synera.com.br"
    - "*.lockari.com"
    - "lockari.com"