---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-gateway-tls
  namespace: envoy-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  secretName: envoy-gateway-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    {{- toYaml .Values.certificates.dnsNames | nindent 10 }}
