apiVersion: v2
name: prometheus
description: A Helm chart for deploying the Prometheus monitoring components.
keywords:
  - prometheus
  - monitoring
  - metrics
type: application
version: "1.0.0"
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: "29.0.1"
    repository: https://prometheus-community.github.io/helm-charts
    alias: kube-stack