
prometheus:
  alertmanager:
    enabled: true
  server:
    ingress:
      enabled: false

gatewayAPI:
  enabled: false
  name: envoy-gateway-envoy-gateway
  namespace: envoy-gateway-system
  sectionName: https
  domains:
  - prometheus.domain.com