
prometheus:
  alertmanager:
    enabled: true
    persistentVolume:
      enabled: false
    # Configura o volume temporário para usar memória (RAM) em vez de disco
    emptyDir:
      medium: "Memory"

  server:
    enabled: true
    persistentVolume:
      enabled: false
    # Configura o volume temporário para usar memória (RAM) em vez de disco
    emptyDir:
      medium: "Memory"
    ingress:
      enabled: false

gatewayAPI:
  enabled: false
  name: envoy-gateway-envoy-gateway
  namespace: envoy-gateway-system
  sectionName: https
  domains:
  - prometheus.domain.com
