apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: provisioning
  source:
    repoURL: https://github.com/Tomelin/k8s-homelab
    targetRevision: HEAD
    path: deploy/infra/backstage
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true