apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: provisioning
  sources:
    - repoURL: https://github.com/Tomelin/k8s-homelab
      targetRevision: main
      path: deploy/applications/gateway-api
      helm:
        valueFiles:
          - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s