apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: provisioning
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.20.0
    chart: external-dns
    helm:
      value: |
        domainFilters: []
        provider:
          name: cloudflare
        sources:
          - gateway-httproute
          - gateway-grpcroute
          - gateway-tlsroute
          - gateway-tcproute
          - gateway-udproute

  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2