apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  labels:
    app: harbor
spec:
  project: provisioning
  source:
    repoURL: https://github.com/Tomelin/k8s-homelab
    targetRevision: HEAD
    path: deploy/infra/harbor
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true