apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: provisioning
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.15.3
    helm:
      values: |
        controller:
          enabled: true
        labels:
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/warn: privileged
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true