apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: provisioning
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.13.0
    helm:
      values: |
        args:
          - --kubelet-preferred-address-types=InternalIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true