apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: provisioning
  source:
    repoURL: https://github.com/Tomelin/k8s-homelab
    targetRevision: main
    path: deploy/infra/postgresql
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: database
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
