---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: provisioning
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: provisioning cluster addons
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/Tomelin/k8s-homelab
  - https://kubernetes-sigs.github.io/metrics-server
  - https://metallb.github.io/metallb
  - https://repo.helmforge.dev