apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argocd
spec:
  destination:
    namespace: workflows
    server: https://kubernetes.default.svc
  project: provisioning
  source:
    chart: argo-workflows
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 1.0.13
    helm:
      values: |
        workflow:
          serviceAccount:
            create: true
            name: "argo-workflow"
          rbac:
            create: true
        server:
          authModes:
          - server  
          httproute:
            enabled: true
            parentRefs:
              - name: envoy-gateway-envoy-gateway
                namespace: envoy-gateway-system
                sectionName: http
            hostnames:
              - workflows.synera.com.br
            # rules:
            # - backendRefs:
            #   - name: workflows
            #     port: 80
            #     weight: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true