apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4" 
spec:
  destination:
    namespace: workflows
    server: https://kubernetes.default.svc
  project: provisioning
  source:
    repoURL: https://github.com/Tomelin/k8s-homelab
    targetRevision: main
    path: deploy/infra/workflows
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true