{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx-tls
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ .Values.certManager.reflectionNamespaces | quote }}
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: {{ .Values.certManager.reflectionNamespaces | quote }}
spec:
  secretName: {{ .Values.certManager.secretName }}
  issuerRef:
    name: {{ .Values.certManager.issuerRef.name }}
    kind: {{ .Values.certManager.issuerRef.kind }}
  dnsNames:
    {{- toYaml .Values.certManager.dnsNames | nindent 4 }}
{{- end }}
