{{- if .Values.argocd.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: argocd-https
  namespace: argocd
spec:
  ingressClassName: {{ .Values.argocd.ingressClassName }}
  {{- if .Values.certManager.enabled }}
  tls:
  - hosts:
    {{- range .Values.argocd.hostnames }}
    - {{ . }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.argocd.hostnames }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
  {{- end }}
{{- end }}
