external-dns:
  env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: apiKey

  domainFilters: 
    - mydomains
  provider:
    name: cloudflare
  sources:
    - gateway-httproute
    - gateway-grpcroute
    - gateway-tlsroute
    - gateway-tcproute
    - gateway-udproute

cloudflare:
  apiToken: mytoken